create table sensors (
                         range_from integer not null,
                         range_to integer not null,
                         id bigint generated by default as identity,
                         model varchar(15) not null,
                         sensor_name varchar(30) unique not null,
                         location varchar(40),
                         description varchar(200),
                         type varchar(255) not null,
                         unit varchar(255) not null,
                         primary key (id)
);

create table users (
                       id bigint generated by default as identity,
                       name varchar(255) unique not null,
                       password varchar(255) not null,
                       roles varchar(255),
                       primary key (id)
);

alter table sensors
add constraint ck_range_validation
check ( range_from < range_to );


alter table  sensors
    add constraint ck_name_length_validation
        check ( char_length(sensor_name) between 3 and 30);